### ISSUE TITLE
AC Syndicate Issue

### ISSUE THREAD

**Issue by AISEXXXD** [gentlegiantJGC/ACExplorer#11]
The program keeps crashing when a model or something is tried to be exported.

**Comment by Edward-Knight** [comment]
What OS are you on and what model were you exporting? Do you have any logs or a stack trace?

**Comment by gentlegiantJGC** [comment]
This program does not support Syndicate

**Comment by Edward-Knight** [comment]
Should we put the supported games on the readme and/or fix the crash?

**Comment by AISEXXXD** [comment]
Can you make it work with Syndicate and do you know any other tools like yours that work with it?

**Comment by AISEXXXD** [comment]
> Should we put the supported games on the readme and/or fix the crash?

Yes it would be helpful for other people!

**Comment by gentlegiantJGC** [comment]
The readme does say it is ACUnity only.
There is Blacksmith
